### ISSUE TITLE
Inconsistencies in tutorial

### ISSUE THREAD

**Issue by newyork-anthonyng** [marko-js-samples/marko-color-picker#2]
This was a great tutorial. 👍 

I wanted to point out some inconsistencies I saw.

## Inconsistencies between `red` and `#ff0000`
From the beginning of the tutorial, the instructions say to use these colors:
```marko
// components/color-picker/index.marko
input.colors = input.colors || [
    'red',
    'green',
    'blue',
    'orange',
    'yellow'
];
```

However, subsequent screenshots show that we are using the `hex` values for the color.

![screen shot 2017-06-02 at 4 22 23 pm](https://cloud.githubusercontent.com/assets/14035529/26743422/b89b3276-47af-11e7-92dd-5d93a69a4128.png)
> Note how this image shows `#ff0000`, not `red`

```js
test('color-picker-header default color', function (context) {
  const output = context.render();
  expect(output.$('div').attr('style')).to.contain('background-color:#ff0000');
});
```
The test example also makes reference to the `hex` value.

> Note how this test also references `#ff0000`, not `red`.

## Final result isn't as expected
Also, the screenshot of the `final result` is not consistent with the previous code snippets. There is no `red` color anywhere.
![screen shot 2017-06-02 at 4 55 19 pm](https://cloud.githubusercontent.com/assets/14035529/26744511/4a8f094c-47b4-11e7-9897-02f08d815950.png)

---
I think the easiest way to fix all of this is to have the screenshot of the `final result` be our source of truth, and update all other code snippets/images to match.
Let me know if you agree, and I can make a PR for this.

**Comment by austinkelleher** [comment]
Yeah I agree with these changes. Thanks for bringing this to my attention. We actually plan sharing this on Reddit on Monday. Let me know if you have time to make the associated changes this weekend (no pressure!), otherwise I will go ahead and make them. Thanks again!

**Comment by newyork-anthonyng** [comment]
@austinkelleher Cool I should have time to make a PR for this by end of day tomorrow, 6/3/17.

**Comment by austinkelleher** [comment]
@newyork-anthonyng awesome thanks I appreciate it.

**Comment by austinkelleher** [comment]
Fixed in #4

**Comment by austinkelleher** [comment]
@newyork-anthonyng https://www.reddit.com/r/javascript/comments/6fndu6/marko_101_building_a_color_picker_component/

**Comment by newyork-anthonyng** [comment]
@austinkelleher Thanks!
