### ISSUE TITLE
Failing test on color-picker-header

### ISSUE THREAD

**Issue by abiyasa** [marko-js-samples/marko-color-picker#7]
I ran `yarn test` and 1 of the tests failed:

```
  1) components/color-picker/components/color-picker-header color-picker-header default color:
     object tested must be an array, an object, or a string, but undefined given
  AssertionError@static/browser-tests-runner/assertion-error$1.0.2/index.js:74:24
  exports@static/browser-tests-runner/chai$3.5.0/lib/chai/utils/expectTypes.js:38:29
  include@static/browser-tests-runner/chai$3.5.0/lib/chai/core/assertions.js:206:18
  assert@static/browser-tests-runner/chai$3.5.0/lib/chai/utils/addChainableMethod.js:84:54
  static/browser-tests-runner/marko-color-picker$0.0.3/components/color-picker/components/color-picker-header/test.js:14:51
  static/browser-tests-runner/marko-devtools$1.0.10/src/commands/test/util/browser-tests-runner/setup.js:20:44
```

I check the [color-picker-header test](https://github.com/marko-js-samples/marko-color-picker/blob/master/components/color-picker/components/color-picker-header/test.js#L14) and the [index.marko](https://github.com/marko-js-samples/marko-color-picker/blob/master/components/color-picker/components/color-picker-header/index.marko#L21),  it seems either:

- forget to support default color support on marko template in case of empty model, or
- test is not valid anymore due to changes in requirement (no default color)

**Comment by abiyasa** [comment]
I personally prefer the 2nd option, not supporting default color so we don't have hardcoded color inside our template. Besides, it also makes sense to have no color for background if none is provided :-)

**Comment by austinkelleher** [comment]
Hey thanks for the report! I agree that the test is now invalid, so I removed it. I wanted to have more than one test in that file to demonstrate that you can easily add multiple tests to a single `test.js`. I've updated the test file to contain a test that validates that the `class` attribute has the `color-picker-header` class.
